=== browscap/browscap/schema/divisions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "properties": {
      "type": "object",
      "properties": {
        "Comment": {
          "type": "string"
        },
        "Version": {
          "type": "string"
        },
        "Browser_Modus": {
          "type": "string"
        },
        "Alpha": {
          "type": "boolean"
        },
        "Beta": {
          "type": "boolean"
        },
        "isFake": {
          "type": "boolean"
        },
        "isAnonymized": {
          "type": "boolean"
        },
        "isModified": {
          "type": "boolean"
        }
      }
    },
    "child": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "match": {
              "type": "string"
            },
            "browser": {
              "type": "string"
            }
          },
          "required": ["match"]
        },
        {
          "anyOf": [
            {
              "properties": {
                "devices": {
                  "type": "object"
                }
              }
            },
            {
              "properties": {
                "device": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "properties": {
            "platforms": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "engine": {
              "type": "string"
            },
            "properties": {
              "$ref": "#/definitions/properties"
            }
          }
        }
      ]
    }
  },

  "type": "object",
  "properties": {
    "division": {
      "type": "string"
    },
    "versions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "integer"
          }
        ]
      }
    },
    "sortIndex": {
      "type": "integer"
    },
    "lite": {
      "type": "boolean"
    },
    "standard": {
      "type": "boolean"
    },
    "userAgents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "userAgent": {
            "type": "string"
          },
          "browser": {
            "type": "string"
          },
          "platform": {
            "type": "string"
          },
          "engine": {
            "type": "string"
          },
          "device": {
            "type": "string"
          },
          "properties": {
            "allOf": [
              {"properties": {
                "Parent": {
                  "type": { "enum": [ "DefaultProperties" ] }
                }
              }
              },
              {"$ref": "#/definitions/properties"},
              {"required": [
                "Parent","Comment"
              ]}
            ]
          },
          "children": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/child"
            }
          }
        },
        "required": [
          "userAgent"
        ]
      }
    },
    "required": [
      "division",
      "sortIndex",
      "lite",
      "standard",
      "userAgents"
    ]
  }
}

=== browscap/browscap/resources/user-agents/browsers/openwave-mobile-browser/openwave-mobile-browser-6-3.json
{
  "division": "Openwave Mobile Browser #MAJORVER#.#MINORVER#",
  "versions": ["6.3"],
  "sortIndex": 8213,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Openwave Mobile Browser #MAJORVER#.#MINORVER#",
      "device": "general Mobile Phone",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Openwave Mobile Browser #MAJORVER#.#MINORVER#",
        "Browser": "Openwave Mobile Browser",
        "Browser_Type": "Browser",
        "Browser_Maker": "Myriad Group",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "BENQ UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "BenQ-CF61/1.00/WAP2.0/MIDP2.0/CLDC1.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "BenQ-CL71/1.00/WAP2.0/MIDP2.0/CLDC1.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "BenQ-E61/1.00/WAP2.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "BenQ-EF51/1.00/WAP2.0/MIDP2.0/CLDC1.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "BenQ-S80/1.00/WAP2.0/MIDP2.0/CLDC1.1 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "BenQ-S81/1.00/WAP2.0/MIDP2.0/CLDC1.1 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "BenQ-S88/1.00/WAP2.0/MIDP2.0/CLDC1.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "BlackBerry8100/4.2* VendorID/124 UP.Browser/5.0*"
        },
        {
          "match": "Cricket-A100/1.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "Cricket-A310/1.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "MOT-W375/* UP.Browser/#MAJORVER#.#MINORVER#.0*"
        },
        {
          "match": "SIEMENS-SFG75/1.00/WAP2.0/MIDP2.0/CLDC1.1 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "UT-GW206/1.0.0 CLDC/CLDC-1.0 MIDP/MIDP-2.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "UTS-7126M/1.0 UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "Nokia* UP.Browser/#MAJORVER#.#MINORVER#*",
          "device": "general Mobile Phone (Nokia)"
        },
        {
          "match": "* UP.Browser/#MAJORVER#.#MINORVER#*"
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/coc-coc-browser/coc-coc-browser-android-48-on.json
{
  "division": "Coc Coc Browser #MAJORVER#.#MINORVER# for Android",
  "versions": [64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48],
  "sortIndex": 883,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Coc Coc Browser #MAJORVER#.#MINORVER# for Android",
      "platform": "Android",
      "engine": "Blink",
      "device": "general Mobile Device (Touch)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Coc Coc Browser #MAJORVER#.#MINORVER#",
        "Browser": "Coc Coc Browser",
        "Browser_Type": "Browser",
        "Browser_Maker": "Coc Coc Company Limited",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/*",
          "devices": {
            "SM-G935F": "Samsung SM-G935F"
          },
          "platforms": [
            "Android_6_0"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/*",
          "devices": {
            "SM-J320H": "Samsung SM-J320H"
          },
          "platforms": [
            "Android_5_1"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/*",
          "devices": {
            "SM-A300H": "Samsung SM-A300H"
          },
          "platforms": [
            "Android_5_0"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/*",
          "devices": {
            "SM-G530H": "Samsung SM-G530H"
          },
          "platforms": [
            "Android_4_4"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/*",
          "devices": {
            "ASUS_T00I": "Asus T00I"
          },
          "platforms": [
            "Android_4_3"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/*",
          "devices": {
            "GT-S7580": "Samsung GT-S7580"
          },
          "platforms": [
            "Android_4_2"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/*",
          "devices": {
            "GT-I9300": "Samsung GT-I9300"
          },
          "platforms": [
            "Android_4_1"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/*",
          "platforms": [
            "Android_7_1", "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0",
            "Android_4_4", "Android_4_3", "Android_4_2", "Android_4_1",
            "Android"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/apps/media-players/77-wabc.json
{
  "division": "77 WABC",
  "sortIndex": 7122,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "77 WABC",
      "engine": "WebKit",
      "device": "general Mobile Device (Apple)",
      "platform": "iOS",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "77 WABC",
        "Browser": "77 WABC",
        "Browser_Type": "Multimedia Player"
      },
      "children": [
        {
          "match": "77%20WABC/* CFNetwork/459*",
          "platforms": [
            "iOS_A_3_1"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/467.12*",
          "platforms": [
            "iOS_A_3_2"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/485.2*",
          "platforms": [
            "iOS_A_4_0"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/485.10*",
          "platforms": [
            "iOS_A_4_1"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/485.12*",
          "platforms": [
            "iOS_A_4_2"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/485.13*",
          "platforms": [
            "iOS_A_4_3"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/548.1*",
          "platforms": [
            "iOS_A_5_1"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/548.0*",
          "platforms": [
            "iOS_A_5_0"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/602*",
          "platforms": [
            "iOS_A_6_0"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/609.1*",
          "platforms": [
            "iOS_A_6_1"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/609*",
          "platforms": [
            "iOS_A_6_0"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/672.0*",
          "platforms": [
            "iOS_A_7_0"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/672.1*",
          "platforms": [
            "iOS_A_7_1"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/711.0*",
          "platforms": [
            "iOS_A_8_0"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/711.1*",
          "platforms": [
            "iOS_A_8_1"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/711.2*",
          "platforms": [
            "iOS_A_8_2"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/711.3*",
          "platforms": [
            "iOS_A_8_3"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/711.4*",
          "platforms": [
            "iOS_A_8_4"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/711.5*",
          "platforms": [
            "iOS_A_8_4"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/758*",
          "platforms": [
            "iOS_A_9_0"
          ]
        },
        {
          "match": "77%20WABC/* CFNetwork/*",
          "platforms": [
            "iOS"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/apps/media-players/downcast.json
{
  "division": "Downcast",
  "sortIndex": 1530,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Downcast",
      "engine": "WebKit",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Downcast",
        "Browser": "Downcast",
        "Browser_Type": "Multimedia Player"
      },
      "children": [
        {
          "match": "iTunes/* Downcast/2.9*",
          "properties": {
            "Version": "2.9"
          }
        },
        {
          "match": "iTunes/* Downcast/2.8*",
          "properties": {
            "Version": "2.8"
          }
        },
        {
          "match": "iTunes/* Downcast/*"
        },
        {
          "match": "Downcast/2.9* (Mac OS X Version 10.11*",
          "platforms": [
            "OSX_10_11"
          ],
          "device": "Macintosh",
          "properties": {
            "Version": "2.9"
          }
        },
        {
          "match": "Downcast/2.9* (Mac OS X*",
          "platforms": [
            "OSX"
          ],
          "device": "Macintosh",
          "properties": {
            "Version": "2.9"
          }
        },
        {
          "match": "Downcast/2.9* (iPhone; iOS 9.2*",
          "platforms": [
            "iOS_A_9_2"
          ],
          "device": "iPhone",
          "properties": {
            "Version": "2.9"
          }
        },
        {
          "match": "Downcast/2.9* (iPhone; iOS*",
          "platforms": [
            "iOS"
          ],
          "device": "iPhone",
          "properties": {
            "Version": "2.9"
          }
        },
        {
          "match": "Downcast/2.9*",
          "properties": {
            "Version": "2.9"
          }
        },
        {
          "match": "Downcast/* (Mac OS X*",
          "platforms": [
            "OSX"
          ],
          "device": "Macintosh"
        },
        {
          "match": "Downcast/* (iPhone; iOS*",
          "platforms": [
            "iOS"
          ],
          "device": "iPhone"
        },
        {
          "match": "Downcast/*"
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/apps/ipnos/relax-melodies.json
{
  "division": "Relax Melodies",
  "sortIndex": 1991,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Relax Melodies",
      "browser": "relax melodies app",
      "engine": "WebKit",
      "device": "general Mobile Phone (Apple)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Relax Melodies"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) Mobile* IpnosInAppBrowser RelaxMelodies",
          "devices": {
            "iPhone": "iPhone"
          },
          "platforms": [
            "iOS_A_11_3", "iOS_A_11_2", "iOS_A_11_1", "iOS_A_11_0",
            "iOS_A_10_3", "iOS_A_10_2", "iOS_A_10_1", "iOS_A_10_0",
            "iOS_A_9_3", "iOS_A_9_2", "iOS_A_9_1", "iOS_A_9_0",
            "iOS_A_8_4", "iOS_A_8_3", "iOS_A_8_2", "iOS_A_8_1", "iOS_A_8_0", "iOS_A_8_0_B",
            "iOS_A_7_1", "iOS_A_7_0",
            "iOS_A"
          ]
        },
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) Mobile* IpnosInAppBrowser RelaxMelodies",
          "devices": {
            "iPad": "iPad"
          },
          "platforms": [
            "iOS_C_11_3", "iOS_C_11_2", "iOS_C_11_1", "iOS_C_11_0",
            "iOS_C_10_3", "iOS_C_10_2", "iOS_C_10_1", "iOS_C_10_0",
            "iOS_C_9_3", "iOS_C_9_2", "iOS_C_9_1", "iOS_C_9_0",
            "iOS_C_8_4", "iOS_C_8_3", "iOS_C_8_2", "iOS_C_8_1", "iOS_C_8_0",
            "iOS_C_7_1", "iOS_C_7_0",
            "iOS_C"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Mobile* IpnosInAppBrowser RelaxMelodies",
          "platforms": [
            "iOS_A",
            "iOS_C"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/android-webview/android-webview-4-1-on.json
{
  "division": "Android WebView #MAJORVER#.#MINORVER#",
  "versions": [5, "4.4", "4.3", "4.2", "4.1"],
  "sortIndex": 953,
  "lite": true,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Android WebView #MAJORVER#.#MINORVER#",
      "platform": "Android",
      "engine": "Blink",
      "device": "general Mobile Phone (Touch)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Android WebView #MAJORVER#.#MINORVER#",
        "Browser": "Android WebView",
        "Browser_Type": "Browser",
        "Browser_Maker": "Google Inc",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*)*applewebkit*(*khtml*like*gecko*)*Version/#MAJORVER#.#MINORVER#*Chrome*Safari*",
          "devices": {
            "Micromax P480": "Micromax P480"
          },
          "platforms": [
            "Android_5_0"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*)*applewebkit*(*khtml*like*gecko*)*Version/#MAJORVER#.#MINORVER#*Chrome*Safari*",
          "devices": {
            "itel it1407": "Itel IT1407",
            "Lenovo TAB S8-50F": "Lenovo S8-50F",
            "Lenovo TAB S8-50L": "Lenovo S8-50L",
            "LG-D415": "LG D415",
            "LG-D800*": "LG D800",
            "LG-D802*": "LG D802",
            "LG-F320K*": "LG F320K",
            "LG-F320L": "LG F320L",
            "LG-F320S": "LG F320S",
            "LGL31L*": "LG L31L",
            "LGL34C*": "LG L34C"
          },
          "platforms": [
            "Android_4_4"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*applewebkit*(*khtml*like*gecko*)*Version/#MAJORVER#.#MINORVER#*Chrome*Safari*",
          "platforms": [
            "Android_7_1", "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0",
            "Android_4_4", "Android_4_3", "Android_4_2", "Android_4_1", "Android_4_0",
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*applewebkit*(*khtml*like*gecko*)*Version/#MAJORVER#.#MINORVER#*Safari*Chrome*",
          "platforms": [
            "Android_7_1", "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0",
            "Android_4_4", "Android_4_3", "Android_4_2", "Android_4_1", "Android_4_0",
            "Android"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/firefox-on-firefoxos/firefox-os-generic.json
{
  "division": "Firefox for FirefoxOS Generic",
  "sortIndex": 3169,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Firefox for FirefoxOS Generic",
      "platform": "FirefoxOS",
      "engine": "Gecko",
      "device": "general Mobile Phone (Touch)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Firefox for FirefoxOS Generic",
        "Browser": "Firefox",
        "Browser_Maker": "Mozilla Foundation",
        "Browser_Type": "Browser"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (Mobile; #DEVICE#; rv:*)*Gecko*Firefox/*",
          "devices": {
            "ALCATELOneTouch4012X*": "Alcatel OT-4012X",
            "ALCATEL ONE TOUCH 4012A": "Alcatel OT-4012A",
            "LG-D300": "LG D300",
            "ZTEOPEN": "ZTE Open"
          }
        },
        {
          "match": "Mozilla/5.0 (Mobile; *rv:*)*Gecko*Firefox/*"
        },
        {
          "match": "Mozilla/5.0 (Tablet; *rv:*)*Gecko*Firefox/*",
          "device": "general Tablet"
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/crawlers/link-checkers/linkchecker.json
{
  "division": "LinkChecker",
  "sortIndex": 670,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "LinkChecker",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Link Checkers",
        "Browser_Type": "Bot/Crawler",
        "Crawler": "true",
        "Browser": "LinkChecker"
      },
      "children": [
        {
          "match": "LinkChecker/7.*",
          "properties": {
            "Version": "7.0",
            "MajorVer": "7"
          }
        },
        {
          "match": "LinkChecker/*"
        }
      ]
    }
  ]
}
