=== browscap/browscap/schema/divisions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "properties": {
      "type": "object",
      "properties": {
        "Comment": {
          "type": "string"
        },
        "Version": {
          "type": "string"
        },
        "Browser_Modus": {
          "type": "string"
        },
        "Alpha": {
          "type": "boolean"
        },
        "Beta": {
          "type": "boolean"
        },
        "isFake": {
          "type": "boolean"
        },
        "isAnonymized": {
          "type": "boolean"
        },
        "isModified": {
          "type": "boolean"
        }
      }
    },
    "child": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "match": {
              "type": "string"
            },
            "browser": {
              "type": "string"
            }
          },
          "required": ["match"]
        },
        {
          "anyOf": [
            {
              "properties": {
                "devices": {
                  "type": "object"
                }
              }
            },
            {
              "properties": {
                "device": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "properties": {
            "platforms": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "engine": {
              "type": "string"
            },
            "properties": {
              "$ref": "#/definitions/properties"
            }
          }
        }
      ]
    }
  },

  "type": "object",
  "properties": {
    "division": {
      "type": "string"
    },
    "versions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "integer"
          }
        ]
      }
    },
    "sortIndex": {
      "type": "integer"
    },
    "lite": {
      "type": "boolean"
    },
    "standard": {
      "type": "boolean"
    },
    "userAgents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "userAgent": {
            "type": "string"
          },
          "browser": {
            "type": "string"
          },
          "platform": {
            "type": "string"
          },
          "engine": {
            "type": "string"
          },
          "device": {
            "type": "string"
          },
          "properties": {
            "allOf": [
              {"properties": {
                "Parent": {
                  "type": { "enum": [ "DefaultProperties" ] }
                }
              }
              },
              {"$ref": "#/definitions/properties"},
              {"required": [
                "Parent","Comment"
              ]}
            ]
          },
          "children": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/child"
            }
          }
        },
        "required": [
          "userAgent"
        ]
      }
    },
    "required": [
      "division",
      "sortIndex",
      "lite",
      "standard",
      "userAgents"
    ]
  }
}

=== browscap/browscap/resources/user-agents/browsers/misc/dillo.json
{
  "division": "Dillo #MAJORVER#.#MINORVER#",
  "versions": ["0.6", "0.7", "0.8", "2.0", "2.1", "3.0"],
  "sortIndex": 2330,
  "lite": false,
  "userAgents": [
    {
      "userAgent": "Dillo #MAJORVER#.#MINORVER#",
      "platform": "Linux",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Dillo #MAJORVER#.#MINORVER#",
        "Browser": "Dillo",
        "Browser_Type": "Browser",
        "Browser_Maker": "the Dillo Project",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "CssVersion": "2",
        "Device_Name": "PC",
        "Device_Maker": "Various",
        "Device_Type": "Desktop",
        "Device_Pointing_Method": "mouse"
      },
      "children": [
        {
          "match": "Dillo\/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "Mozilla\/5.0 (compatible; X11; Dillo\/#MAJORVER#.#MINORVER#*)"
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/crawlers/general-crawlers/grouphigh-bot.json
{
  "division": "GroupHigh Bot",
  "sortIndex": 170,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "GroupHigh Bot",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "GroupHigh Bot",
        "Browser": "GroupHigh Bot",
        "Browser_Maker": "GroupHigh LLC",
        "Browser_Type": "Bot/Crawler",
        "Crawler": "true"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (compatible; GroupHigh/1.0*",
          "properties": {
            "Version": "1.0"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; GroupHigh/*"
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/115-browser/115-browser-generic.json
{
  "division": "115 Browser Generic",
  "sortIndex": 955,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "115 Browser Generic",
      "engine": "Blink",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "115 Browser Generic",
        "Browser": "115 Browser",
        "Browser_Type": "Browser",
        "Browser_Maker": "115.com"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/* Safari/* 115Browser/*",
          "device": "Windows Desktop",
          "platforms": [
            "Win10_x64", "Win10_64", "Win10_32", "Win10_x64_B", "Win10_64_B", "Win10_32_B",
            "Win8_1_x64", "Win8_1_64", "Win8_1_32",
            "Win8_x64", "Win8_64", "Win8_32",
            "Win7_x64", "Win7_64", "Win7_32",
            "Vista_64", "Vista_32"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/* Safari/* 115Browser/*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_12", "OSX_10_11", "OSX_10_10",
            "OSX"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/apps/electron/electron-1-2-on.json
{
  "division": "Electron #MAJORVER#.#MINORVER#",
  "versions": [2, "1.8", "1.7", "1.6", "1.4", "1.3", "1.2"],
  "sortIndex": 2220,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Electron #MAJORVER#.#MINORVER#",
      "browser": "electron",
      "engine": "Blink",
      "device": "Windows Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Electron #MAJORVER#.#MINORVER#",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) * Chrome/* Electron/#MAJORVER#.#MINORVER#* Safari/*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_13", "OSX_10_12",
            "OSX_10_11", "OSX_10_10", "OSX_10_9",
            "OSX"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/* Electron/#MAJORVER#.#MINORVER#* Safari/*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_13", "OSX_10_12",
            "OSX_10_11", "OSX_10_10", "OSX_10_9",
            "OSX"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) * Chrome/* Electron/#MAJORVER#.#MINORVER#* Safari/*",
          "device": "Windows Desktop",
          "platforms": [
            "Win10_x64_B", "Win10_64_B", "Win10_32_B",
            "Win10_x64", "Win10_64", "Win10_32",
            "Win8_1_x64", "Win8_1_64", "Win8_1_32",
            "Win8_x64", "Win8_64", "Win8_32",
            "Win7_x64", "Win7_64", "Win7_32",
            "Windows"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/* Electron/#MAJORVER#.#MINORVER#* Safari/*",
          "device": "Windows Desktop",
          "platforms": [
            "Win10_x64_B", "Win10_64_B", "Win10_32_B",
            "Win10_x64", "Win10_64", "Win10_32",
            "Win8_1_x64", "Win8_1_64", "Win8_1_32",
            "Win8_x64", "Win8_64", "Win8_32",
            "Win7_x64", "Win7_64", "Win7_32",
            "Windows"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) * Chrome/* Electron/#MAJORVER#.#MINORVER#* Safari/*",
          "device": "Linux Desktop",
          "platforms": [
            "Linux_64", "Linux"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/* Electron/#MAJORVER#.#MINORVER#* Safari/*",
          "device": "Linux Desktop",
          "platforms": [
            "Linux_64", "Linux"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/cm-browser/cm-browser.json
{
  "division": "CM Browser",
  "sortIndex": 883,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "CM Browser",
      "platform": "Android",
      "engine": "Blink",
      "device": "general Mobile Phone (Touch)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "CM Browser",
        "Browser": "CM Browser",
        "Browser_Type": "Browser",
        "Browser_Maker": "Cheetah Mobile"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "SM-G920P": "Samsung SM-G920P",
            "SM-G930A": "Samsung SM-G930A",
            "SM-G935P": "Samsung SM-G935P",
            "SM-G935V": "Samsung SM-G935V",
            "SM-N920V": "Samsung SM-N920V",
            "SM-S320VL": "Samsung SM-S320VL"
          },
          "platforms": [
            "Android_6_0"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "LGLS770": "LG LS770"
          },
          "platforms": [
            "Android_5_1"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "GT-N7105": "Samsung GT-N7105",
            "Honor": "Huawei U8860"
          },
          "platforms": [
            "Android_5_0"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "K00E": "Asus K00E"
          },
          "platforms": [
            "Android_5_0", "Android_4_4"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "D5303": "Sony D5303",
            "HTC Desire 820": "HTC Desire 820",
            "HUAWEI HN3-U01": "Huawei HN3-U01",
            "Lenovo A328": "Lenovo A328",
            "Lenovo A3500-FL": "Lenovo A3500-FL",
            "LG-D295": "LG D295",
            "LG-D410": "LG D410",
            "LG-F200K": "LG F200K",
            "LG-F220K": "LG F220K",
            "MTC SMART Run": "MTC SMART Run",
            "SM-G530H": "Samsung SM-G530H",
            "SM-N750": "Samsung SM-N750",
            "Techno 9.7 3G": "BB-Mobile Techno 9.7 3G",
            "Tornado": "KAZAM Tornado 348"
          },
          "platforms": [
            "Android_4_4"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "Lenovo B8000-H": "Lenovo B8000-H"
          },
          "platforms": [
            "Android_4_4", "Android_4_3", "Android_4_2"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "K1 turbo": "Kingzone KZ-168"
          },
          "platforms": [
            "Android_4_3"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "HUAWEI P6 S-U06": "Huawei P6 S-U06",
            "Lenovo A859": "Lenovo A859",
            "PMP5785C3G_QUAD": "Prestigio PMP5785C3G_QUAD",
            "U51GT": "Cube U51GT",
            "Vega": "Advent P10AN01"
          },
          "platforms": [
            "Android_4_2"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "devices": {
            "Lenovo A706_ROW": "Lenovo A706"
          },
          "platforms": [
            "Android_4_1"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Version/*Chrome/*Safari/* ACHEETAHI/*",
          "platforms": [
            "Android_7_1", "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0",
            "Android_4_4", "Android_4_3", "Android_4_2", "Android_4_1", "Android_4_0",
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Safari/* ACHEETAHI/*",
          "devices": {
            "K00E": "Asus K00E"
          },
          "engine": "WebKit",
          "platforms": [
            "Android_5_0", "Android_4_4"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Safari/* ACHEETAHI/*",
          "devices": {
            "LG-D295": "LG D295",
            "PAP5450": "Prestigio PAP5450"
          },
          "engine": "WebKit",
          "platforms": [
            "Android_4_4"
          ]
        },
         {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Safari/* ACHEETAHI/*",
          "devices": {
            "Lenovo B8000-H": "Lenovo B8000-H"
          },
          "engine": "WebKit",
          "platforms": [
            "Android_4_4", "Android_4_3", "Android_4_2"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Safari/* ACHEETAHI/*",
          "devices": {
            "C1904": "Sony C1904",
            "K1 turbo": "Kingzone KZ-168",
            "SM-N900V": "Samsung SM-N900V"
          },
          "engine": "WebKit",
          "platforms": [
            "Android_4_3"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Safari/* ACHEETAHI/*",
          "devices": {
            "A400": "Celkon A400",
            "ALCATEL ONE TOUCH 6040D": "Alcatel OT-6040D",
            "AP-708": "Assistant AP-708",
            "GT-I8200": "Samsung GT-I8200",
            "GT-I9060": "Samsung GT-I9060",
            "HUAWEI P6 S-U06": "Huawei P6 S-U06",
            "IQ434": "Fly IQ434",
            "IQ456": "Fly IQ456",
            "Keneksi-SUN": "Keneksi Sun",
            "KT07": "KingTop KT07",
            "Lenovo A3000-H": "Lenovo A3000-H",
            "Lenovo A369i": "Lenovo A369i",
            "Lenovo A680_ROW": "Lenovo A680",
            "Lenovo A859": "Lenovo A859",
            "MTC 978": "MTC 978",
            "OYSTERS T80 3G": "Oysters T80 3G",
            "Philips W3500": "Philips W3500",
            "PMP5785C3G_QUAD": "Prestigio PMP5785C3G_QUAD",
            "QUANTUM_700m": "GOCLEVER Quantum 700m",
            "RM-560": "Ross&Moor RM-560",
            "T108": "Twinovo T108",
            "TT7022MG_O72": "Digma TT7022MG-O72",
            "Turbo Pad 500": "TurboPad 500",
            "TurboPad TP705": "TurboPad TP705",
            "U51GT": "Cube U51GT",
            "U55GT": "Cube U55GT",
            "Vega": "Advent P10AN01",
            "W200": "ThL W200",
            "W6500": "Philips W6500"
          },
          "engine": "WebKit",
          "platforms": [
            "Android_4_2"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Safari/* ACHEETAHI/*",
          "devices": {
            "Desire 700 dual sim": "HTC Desire 700",
            "H7100": "Feiteng H7100",
            "IQ430": "Fly IQ430",
            "LC0720C": "3Q LC0720C",
            "Lenovo A706_ROW": "Lenovo A706",
            "Micromax A59": "Micromax A59",
            "N1010": "ViewSonic N1010",
            "RMD-855": "Ritmix RMD-855",
            "Surfer 8.31 3G": "Explay Surfer 8.31 3G",
            "X Point": "TeXet TM-4077"
          },
          "engine": "WebKit",
          "platforms": [
            "Android_4_1"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) applewebkit* (*khtml*like*gecko*) Version/*Safari/* ACHEETAHI/*",
          "devices": {
            "chagall": "Pegatron Chagall",
            "RMD-757": "Ritmix RMD-757",
            "S4702M": "DNS S4702M",
            "TM-5377": "TeXet TM-5377"
          },
          "engine": "WebKit",
          "platforms": [
            "Android_4_0"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Version/*Safari/* ACHEETAHI/*",
          "engine": "WebKit",
          "platforms": [
            "Android_7_1", "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0",
            "Android_4_4", "Android_4_3", "Android_4_2", "Android_4_1", "Android_4_0",
            "Android"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/coc-coc-browser/coc-coc-browser-winmobile-58-on.json
{
  "division": "Coc Coc Browser #MAJORVER#.#MINORVER# for Windows Phone",
  "versions": [64, 63, 62, 61, 60, 59, 58],
  "sortIndex": 883,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Coc Coc Browser #MAJORVER#.#MINORVER# for Windows Phone",
      "platform": "WinPhone",
      "engine": "WebKit",
      "device": "general Mobile Device (Touch)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Coc Coc Browser #MAJORVER#.#MINORVER#",
        "Browser": "Coc Coc Browser",
        "Browser_Type": "Browser",
        "Browser_Maker": "Coc Coc Company Limited",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE#) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/* Edge/*",
          "devices": {
            "Lumia 735": "Nokia Lumia 735"
          },
          "platforms": [
            "WinPhone10"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) coc_coc_browser/#MAJORVER#.* Chrome/* Safari/* Edge/*",
          "platforms": [
            "WinPhone10", "WinPhone8.1",
            "WinPhone"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/crawlers/image-crawlers/gwp-images.json
{
  "division": "GWPImages",
  "sortIndex": 401,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "GWPImages",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "GWPImages",
        "Browser": "GWPImages",
        "Browser_Type": "Bot/Crawler",
        "Browser_Maker": "unknown",
        "Crawler": "true"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (compatible; GWPImages/1.0*",
          "properties": {
            "Version": "1.0",
            "MajorVer": "1",
            "MinorVer": "0"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; GWPImages/*"
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/crawlers/microsoft/adidxbot.json
{
  "division": "adidxbot",
  "sortIndex": 1231,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "adidxbot",
      "properties": {
        "Parent": "DefaultProperties",
        "Browser_Type": "Bot/Crawler",
        "Browser_Maker": "Microsoft Corporation",
        "Comment": "MSN",
        "Browser": "adidxbot",
        "Crawler": "true"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM# Trident/7.* IEMobile/*) like Gecko (compatible; adidxbot/2.0*",
          "engine": "Trident_7",
          "device": "general Mobile Device",
          "platforms": [
            "WinPhone8.1",
            "WinPhone"
          ],
          "properties": {
            "Version": "2.0"
          }
        },
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) Version/* Mobile/* Safari/* (compatible; adidxbot/2.0*",
          "engine": "WebKit",
          "devices": {
            "iPhone": "iPhone",
            "iPad": "iPad",
            "iPod": "iPod Touch"
          },
          "platforms": [
            "iOS_A_7_0",
            "iOS_A"
          ],
          "properties": {
            "Version": "2.0"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; adidxbot/2.0; ?http://www.bing.com/bingbot.htm)",
          "properties": {
            "Version": "2.0"
          }
        },
        {
          "match": "adidxbot/1.1 (?http://search.msn.com/msnbot.htm)",
          "properties": {
            "Version": "1.1"
          }
        },
        {
          "match": "adidxbot/2.0*",
          "properties": {
            "Version": "2.0"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; adidxbot/*; ?http://www.bing.com/bingbot.htm)"
        },
        {
          "match": "adidxbot/*"
        }
      ]
    }
  ]
}
