=== browscap/browscap/schema/divisions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "properties": {
      "type": "object",
      "properties": {
        "Comment": {
          "type": "string"
        },
        "Version": {
          "type": "string"
        },
        "Browser_Modus": {
          "type": "string"
        },
        "Alpha": {
          "type": "boolean"
        },
        "Beta": {
          "type": "boolean"
        },
        "isFake": {
          "type": "boolean"
        },
        "isAnonymized": {
          "type": "boolean"
        },
        "isModified": {
          "type": "boolean"
        }
      }
    },
    "child": {
      "allOf": [
        {
          "type": "object",
          "properties": {
            "match": {
              "type": "string"
            },
            "browser": {
              "type": "string"
            }
          },
          "required": ["match"]
        },
        {
          "anyOf": [
            {
              "properties": {
                "devices": {
                  "type": "object"
                }
              }
            },
            {
              "properties": {
                "device": {
                  "type": "string"
                }
              }
            }
          ]
        },
        {
          "properties": {
            "platforms": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "engine": {
              "type": "string"
            },
            "properties": {
              "$ref": "#/definitions/properties"
            }
          }
        }
      ]
    }
  },

  "type": "object",
  "properties": {
    "division": {
      "type": "string"
    },
    "versions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "integer"
          }
        ]
      }
    },
    "sortIndex": {
      "type": "integer"
    },
    "lite": {
      "type": "boolean"
    },
    "standard": {
      "type": "boolean"
    },
    "userAgents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "userAgent": {
            "type": "string"
          },
          "browser": {
            "type": "string"
          },
          "platform": {
            "type": "string"
          },
          "engine": {
            "type": "string"
          },
          "device": {
            "type": "string"
          },
          "properties": {
            "allOf": [
              {"properties": {
                "Parent": {
                  "type": { "enum": [ "DefaultProperties" ] }
                }
              }
              },
              {"$ref": "#/definitions/properties"},
              {"required": [
                "Parent","Comment"
              ]}
            ]
          },
          "children": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/child"
            }
          }
        },
        "required": [
          "userAgent"
        ]
      }
    },
    "required": [
      "division",
      "sortIndex",
      "lite",
      "standard",
      "userAgents"
    ]
  }
}

=== browscap/browscap/resources/user-agents/crawlers/general-crawlers/cfnetwork.json
{
  "division": "CFNetwork",
  "sortIndex": 2000,
  "lite": false,
  "userAgents": [
    {
      "userAgent": "CFNetwork",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "CFNetwork",
        "Browser": "CFNetwork",
        "Browser_Type": "Bot/Crawler",
        "Crawler": "true"
      },
      "children": [
        {
          "match": "*CFNetwork*",
          "properties": {
            "Browser": "CFNetwork"
          }
        },
        {
          "match": "CFNetwork\/*",
          "properties": {
            "Browser": "CFNetwork"
          }
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/kazehakase/kazehakase.json
{
  "division": "Kazehakase #MAJORVER#.#MINORVER#",
  "versions": ["0.5", "0.4"],
  "sortIndex": 2460,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Kazehakase #MAJORVER#.#MINORVER#",
      "platform": "Linux",
      "engine": "Gecko",
      "device": "Linux Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Kazehakase #MAJORVER#.#MINORVER#",
        "Browser": "Kazehakase",
        "Browser_Type": "Browser",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Win32": "false",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true"
      },
      "children": [
        {
          "match": "Mozilla\/5.0 (#PLATFORM#) Gecko* Firefox* Kazehakase\/#MAJORVER#.#MINORVER#*",
          "platforms": [
            "Linux_64", "Linux_32", "Linux"
          ]
        },
        {
          "match": "Mozilla\/5.0 (#PLATFORM#) Gecko* Kazehakase\/#MAJORVER#.#MINORVER#*",
          "platforms": [
            "Linux_64", "Linux_32", "Linux"
          ]
        },
        {
          "match": "Mozilla\/5.0 (#PLATFORM#) Gecko* Firefox* Kazehakase\/#MAJORVER#.#MINORVER#*",
          "device": "general Desktop",
          "platforms": [
            "FreeBSD"
          ]
        },
        {
          "match": "Mozilla\/5.0 (#PLATFORM#) Gecko* Kazehakase\/#MAJORVER#.#MINORVER#*",
          "device": "general Desktop",
          "platforms": [
            "FreeBSD"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/waterfox/waterfox-41-to-50-1.json
{
  "division": "Waterfox #MAJORVER#.#MINORVER#",
  "versions": ["50.1", 50, 49, 48, 47, 46, 45, 44, 43, 42, 41],
  "sortIndex": 3143,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Waterfox #MAJORVER#.#MINORVER#",
      "engine": "Gecko_Major_Dynamic",
      "device": "general Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Waterfox #MAJORVER#.#MINORVER#",
        "Browser": "Waterfox",
        "Browser_Type": "Browser",
        "Browser_Maker": "www.waterfoxproject.org",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) Gecko* Firefox/* Waterfox/#MAJORVER#.#MINORVER#*",
          "device": "Linux Desktop",
          "platforms": [
            "Linux_32_on_x64", "Linux_64", "Linux_32", "Linux"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) Gecko* Firefox/* Waterfox/#MAJORVER#.#MINORVER#*",
          "device": "Windows Desktop",
          "platforms": [
            "NT4_64", "NT4_x64",
            "Vista_32", "Vista_x64", "Vista_64",
            "Win7_x64_2", "Win7_x64", "Win7_64", "Win7_32",
            "Win8_x64", "Win8_64", "Win8_32",
            "Win8_1_x64", "Win8_1_64", "Win8_1_32",
            "Win10_x64", "Win10_64", "Win10_32", "Win10_x64_B", "Win10_64_B", "Win10_32_B",
            "Windows"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) Gecko* Firefox/* Waterfox/#MAJORVER#.#MINORVER#*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_12", "OSX_10_11", "OSX_10_10", "OSX_10_9", "OSX_10_8", "OSX_10_7", "OSX_10_6", "OSX_10_5",
            "OSX"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/blackberry/blackberry-10-1-on.json
{
  "division": "BlackBerry #MAJORVER#.#MINORVER#",
  "versions": ["10.3", "10.2", "10.1"],
  "sortIndex": 2360,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "BlackBerry #MAJORVER#.#MINORVER#",
      "platform": "RIMOS_10_X",
      "engine": "WebKit",
      "device": "general Mobile Phone (Blackberry)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "BlackBerry #MAJORVER#.#MINORVER#",
        "Browser": "BlackBerry",
        "Browser_Type": "Browser",
        "Browser_Maker": "Research In Motion Limited",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (BB10; #DEVICE#) applewebkit* (*khtml*like*gecko*) Version/#MAJORVER#.#MINORVER#*Safari/*",
          "devices": {
            "Kbd": "Blackberry KBD",
            "Touch": "Blackberry Z10"
          }
        },
        {
          "match": "Mozilla/5.0 (BB10; *) applewebkit* (*khtml*like*gecko*) Version/#MAJORVER#.#MINORVER#*Safari/*"
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/firefox-on-kaios/firefox-kaios-generic.json
{
  "division": "Firefox for KaiOS Generic",
  "sortIndex": 3169,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Firefox for KaiOS Generic",
      "browser": "firefox",
      "platform": "KaiOS",
      "engine": "Gecko",
      "device": "general Mobile Phone",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Firefox for KaiOS Generic"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (Mobile; *rv:*)*Gecko*Firefox/#PLATFORM#",
          "platforms": [
            "KaiOS_2_0",
            "KaiOS_1_0",
            "KaiOS"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/crawlers/copyright-plagiarism/copyright-plagiarism.json
{
  "division": "Copyright/Plagiarism",
  "sortIndex": 320,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Copyright/Plagiarism",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Copyright/Plagiarism",
        "Browser": "Copyright/Plagiarism",
        "Browser_Type": "Bot/Crawler",
        "Crawler": "true"
      },
      "children": [
        {
          "match": "BDFetch",
          "properties": {
            "Browser": "BDFetch"
          }
        },
        {
          "match": "copyright sheriff (*)",
          "properties": {
            "Browser": "copyright sheriff"
          }
        },
        {
          "match": "CopyRightCheck*",
          "properties": {
            "Browser": "CopyRightCheck"
          }
        },
        {
          "match": "FairAd Client*",
          "properties": {
            "Browser": "FairAd Client"
          }
        },
        {
          "match": "iCopyright Conductor*",
          "properties": {
            "Browser": "iCopyright Conductor"
          }
        },
        {
          "match": "IPiumBot laurion(dot)com",
          "properties": {
            "Browser": "IPiumBot"
          }
        },
        {
          "match": "IWAgent/*",
          "properties": {
            "Browser": "Brand Protect"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; DKIMRepBot/*)",
          "properties": {
            "Browser": "DKIMRepBot"
          }
        },
        {
          "match": "SlySearch/*",
          "properties": {
            "Browser": "SlySearch"
          }
        },
        {
          "match": "TutorGigBot/*",
          "properties": {
            "Browser": "TutorGig"
          }
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/apps/site-monitors/site-con.json
{
  "division": "SiteCon",
  "sortIndex": 491,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "SiteCon",
      "platform": "Linux",
      "engine": "WebKit",
      "device": "Linux Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "SiteCon",
        "Browser": "SiteCon",
        "Browser_Maker": "NCC Group.",
        "Browser_Type": "Application",
        "Crawler": "false"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) AppleWebKit/* (*khtml*like*gecko*) SiteCon/8.10*",
          "properties": {
            "Version": "8.10",
            "MajorVer": "8",
            "MinorVer": "10"
          },
          "platforms": [
            "Linux"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) AppleWebKit/* (*khtml*like*gecko*) SiteCon/8.8*",
          "properties": {
            "Version": "8.8",
            "MajorVer": "8",
            "MinorVer": "8"
          },
          "platforms": [
            "Linux"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) AppleWebKit/* (*khtml*like*gecko*) SiteCon/*",
          "platforms": [
            "Linux"
          ]
        }
      ]
    }
  ]
}

=== browscap/browscap/resources/user-agents/browsers/galeon/galeon-1-x-on.json
{
  "division": "Galeon #MAJORVER#.#MINORVER#",
  "versions": [2, "1.3", "1.2", "1.1", 1],
  "sortIndex": 2380,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Galeon #MAJORVER#.#MINORVER#",
      "platform": "Linux",
      "device": "Linux Desktop",
      "engine": "Gecko",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Galeon #MAJORVER#.#MINORVER#",
        "Browser": "Galeon",
        "Browser_Type": "Browser",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "CssVersion": "2"
      },
      "children": [
        {
          "match": "Mozilla\/5.0 (#PLATFORM#) Gecko* Galeon\/#MAJORVER#.#MINORVER#* Firefox\/*",
          "platforms": [
            "Linux_32", "Linux"
          ]
        },
        {
          "match": "Mozilla\/5.0 (#PLATFORM#) Gecko* Galeon\/#MAJORVER#.#MINORVER#*",
          "platforms": [
            "Linux_32", "Linux"
          ]
        },
        {
          "match": "Mozilla\/5.0 (#PLATFORM#) Gecko* Galeon\/#MAJORVER#.#MINORVER#*",
          "device": "general Desktop",
          "platforms": [
            "FreeBSD"
          ]
        },
        {
          "match": "Mozilla\/5.0 Galeon\/#MAJORVER#.#MINORVER#* (#PLATFORM#)*",
          "platforms": [
            "Linux_32", "Linux"
          ]
        }
      ]
    }
  ]
}
